let hole = { isRock: false, visited: true, win: false };
let rock = { isRock: true, visited: false, win: false };
let ground = { isRock: false, visited: false, win: false };
let win = { isRock: false, visited: false, win: true };

export var level1 = [
  [
    { ...rock },
    { ...rock },
    { ...ground },
    { ...rock },
    { ...rock },
    { ...rock },
    { ...ground },
    { ...rock },
    { ...rock },
    { ...rock },
    { ...rock },
    { ...rock },
  ],
  [
    { ...rock },
    { ...ground },
    { ...hole },
    { ...hole },
    { ...ground },
    { ...ground },
    { ...rock },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...rock },
  ],
  [
    { ...rock },
    { ...ground },
    { ...rock },
    { ...hole },
    { ...hole },
    { ...rock },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...rock },
  ],
  [
    { ...rock },
    { ...ground },
    { ...hole },
    { ...hole },
    { ...hole },
    { ...hole },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...rock },
  ],
  [
    { ...rock },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...rock },
  ],
  [
    { ...ground },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...ground },
  ],
  [
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...rock },
  ],
  [
    { ...rock },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...rock },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...rock },
  ],
  [
    { ...rock },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...rock },
  ],
  [
    { ...rock },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...ground },
    { ...rock },
    { ...ground },
    { ...ground },
    { ...win },
    { ...rock },
  ],

  [
    { ...rock },
    { ...rock },
    { ...ground },
    { ...rock },
    { ...rock },
    { ...ground },
    { ...rock },
    { ...rock },
    { ...rock },
    { ...rock },
    { ...rock },
    { ...rock },
  ],
];
